package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/dipeshmalviya/subscription-billing-platform/subscription/internal/graphql/model"
	"github.com/google/uuid"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignupInput) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Signup - signup"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// CreateSubscription is the resolver for the createSubscription field.
func (r *mutationResolver) CreateSubscription(ctx context.Context, input model.CreateSubscriptionInput) (*model.UserSubscription, error) {
	panic(fmt.Errorf("not implemented: CreateSubscription - createSubscription"))
}

// CancelSubscription is the resolver for the cancelSubscription field.
func (r *mutationResolver) CancelSubscription(ctx context.Context, id uuid.UUID) (*model.UserSubscription, error) {
	panic(fmt.Errorf("not implemented: CancelSubscription - cancelSubscription"))
}

// CreatePlan is the resolver for the createPlan field.
func (r *mutationResolver) CreatePlan(ctx context.Context, input model.CreatePlanInput) (*model.Plan, error) {
	panic(fmt.Errorf("not implemented: CreatePlan - createPlan"))
}

// DeactivatePlan is the resolver for the deactivatePlan field.
func (r *mutationResolver) DeactivatePlan(ctx context.Context, id uuid.UUID) (*model.Plan, error) {
	panic(fmt.Errorf("not implemented: DeactivatePlan - deactivatePlan"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Customer, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Plans is the resolver for the plans field.
func (r *queryResolver) Plans(ctx context.Context) ([]*model.Plan, error) {
	panic(fmt.Errorf("not implemented: Plans - plans"))
}

// MySubscriptions is the resolver for the mySubscriptions field.
func (r *queryResolver) MySubscriptions(ctx context.Context) ([]*model.UserSubscription, error) {
	panic(fmt.Errorf("not implemented: MySubscriptions - mySubscriptions"))
}

// MyInvoices is the resolver for the myInvoices field.
func (r *queryResolver) MyInvoices(ctx context.Context) ([]*model.Invoice, error) {
	panic(fmt.Errorf("not implemented: MyInvoices - myInvoices"))
}

// Subscription is the resolver for the subscription field.
func (r *queryResolver) Subscription(ctx context.Context, id uuid.UUID) (*model.UserSubscription, error) {
	panic(fmt.Errorf("not implemented: Subscription - subscription"))
}

// AllCustomers is the resolver for the allCustomers field.
func (r *queryResolver) AllCustomers(ctx context.Context, limit *int32, offset *int32) ([]*model.Customer, error) {
	panic(fmt.Errorf("not implemented: AllCustomers - allCustomers"))
}

// CustomerInvoices is the resolver for the customerInvoices field.
func (r *queryResolver) CustomerInvoices(ctx context.Context, customerID uuid.UUID) ([]*model.Invoice, error) {
	panic(fmt.Errorf("not implemented: CustomerInvoices - customerInvoices"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
