// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AuthPayload struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	Customer     *Customer `json:"customer"`
}

type CreatePlanInput struct {
	Name            string          `json:"name"`
	PriceCents      int32           `json:"priceCents"`
	Currency        string          `json:"currency"`
	BillingInterval BillingInterval `json:"billingInterval"`
}

type CreateSubscriptionInput struct {
	PlanID uuid.UUID `json:"planId"`
}

type Customer struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FullName  string    `json:"fullName"`
	Role      Role      `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

type Invoice struct {
	ID           uuid.UUID         `json:"id"`
	Subscription *UserSubscription `json:"subscription"`
	AmountCents  int32             `json:"amountCents"`
	Currency     string            `json:"currency"`
	Status       InvoiceStatus     `json:"status"`
	DueDate      time.Time         `json:"dueDate"`
	PaidAt       *time.Time        `json:"paidAt,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Plan struct {
	ID              uuid.UUID       `json:"id"`
	Name            string          `json:"name"`
	PriceCents      int32           `json:"priceCents"`
	Currency        string          `json:"currency"`
	BillingInterval BillingInterval `json:"billingInterval"`
	IsActive        bool            `json:"isActive"`
}

type Query struct {
}

type SignupInput struct {
	Email    string `json:"email"`
	FullName string `json:"fullName"`
	Password string `json:"password"`
}

type UserSubscription struct {
	ID                 uuid.UUID          `json:"id"`
	Customer           *Customer          `json:"customer"`
	Plan               *Plan              `json:"plan"`
	Status             SubscriptionStatus `json:"status"`
	CurrentPeriodStart time.Time          `json:"currentPeriodStart"`
	CurrentPeriodEnd   time.Time          `json:"currentPeriodEnd"`
	CanceledAt         *time.Time         `json:"canceledAt,omitempty"`
}

type BillingInterval string

const (
	BillingIntervalMonthly BillingInterval = "MONTHLY"
	BillingIntervalYearly  BillingInterval = "YEARLY"
)

var AllBillingInterval = []BillingInterval{
	BillingIntervalMonthly,
	BillingIntervalYearly,
}

func (e BillingInterval) IsValid() bool {
	switch e {
	case BillingIntervalMonthly, BillingIntervalYearly:
		return true
	}
	return false
}

func (e BillingInterval) String() string {
	return string(e)
}

func (e *BillingInterval) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BillingInterval(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BillingInterval", str)
	}
	return nil
}

func (e BillingInterval) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BillingInterval) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BillingInterval) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InvoiceStatus string

const (
	InvoiceStatusPending InvoiceStatus = "PENDING"
	InvoiceStatusPaid    InvoiceStatus = "PAID"
	InvoiceStatusFailed  InvoiceStatus = "FAILED"
	InvoiceStatusVoid    InvoiceStatus = "VOID"
)

var AllInvoiceStatus = []InvoiceStatus{
	InvoiceStatusPending,
	InvoiceStatusPaid,
	InvoiceStatusFailed,
	InvoiceStatusVoid,
}

func (e InvoiceStatus) IsValid() bool {
	switch e {
	case InvoiceStatusPending, InvoiceStatusPaid, InvoiceStatusFailed, InvoiceStatusVoid:
		return true
	}
	return false
}

func (e InvoiceStatus) String() string {
	return string(e)
}

func (e *InvoiceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvoiceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvoiceStatus", str)
	}
	return nil
}

func (e InvoiceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvoiceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvoiceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin    Role = "ADMIN"
	RoleCustomer Role = "CUSTOMER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleCustomer,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleCustomer:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusActive   SubscriptionStatus = "ACTIVE"
	SubscriptionStatusCanceled SubscriptionStatus = "CANCELED"
	SubscriptionStatusPastDue  SubscriptionStatus = "PAST_DUE"
	SubscriptionStatusPaused   SubscriptionStatus = "PAUSED"
)

var AllSubscriptionStatus = []SubscriptionStatus{
	SubscriptionStatusActive,
	SubscriptionStatusCanceled,
	SubscriptionStatusPastDue,
	SubscriptionStatusPaused,
}

func (e SubscriptionStatus) IsValid() bool {
	switch e {
	case SubscriptionStatusActive, SubscriptionStatusCanceled, SubscriptionStatusPastDue, SubscriptionStatusPaused:
		return true
	}
	return false
}

func (e SubscriptionStatus) String() string {
	return string(e)
}

func (e *SubscriptionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubscriptionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubscriptionStatus", str)
	}
	return nil
}

func (e SubscriptionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubscriptionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubscriptionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
